Module 8
jaybee1971/DevOps-Course-Starter pull request #11
Opened 2021-03-02 11:24 UTC by jaybee1971

All steps done + looked into using the buildkit to use caching in Travis when running docker build and docker-compose.
https://travis-ci.com/github/jaybee1971/DevOps-Course-Starter
https://hub.docker.com/repository/docker/jaybee1971/todo_app
https://jaybee1971-todoapp.herokuapp.com/

2021-03-10 16:00 UTC, hugh-emerson requested changes
Generally looks good. I've left a few suggestions but there's just one line that **needs** fixing - your login command for the Heroku Docker registry. See my other comment for details.

2021-03-10 16:00 UTC, hugh-emerson commented on Dockerfile
> +ENV PORT=${PORT}
This doesn't do anything. `ENV` is set at build time, and so doesn't have access to $PORT. It's for setting an environment variable in case the variable doesn't get set when running the container. Even if it could access $PORT, it still wouldn't do anything because you'd be setting a variable to equal itself.

2021-03-10 16:00 UTC, hugh-emerson commented on docker_push
> +echo docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
Do you mean `echo "$HEROKU_API_KEY" | docker login -u <<your Heroku email>> --password-stdin registry.heroku.com`?

Currently your deployment isn't doing working. This line is simply echoing the text `docker login ... etc` to the terminal and then the push fails because you're not logged in.
See https://travis-ci.com/github/jaybee1971/DevOps-Course-Starter/builds/218679223
Lines 1639-1667

Problems like this should get caught more easily if you add `set -e` to the top of the script. It means that if any single line in the file returns a non-zero exit code (i.e. something failed), then the script itself will stop early and return that too.

2021-03-10 16:00 UTC, hugh-emerson commented on .travis.yml
> +  - docker-compose --file docker-compose-travis.yml up --exit-code-from todoapp
Can't you skip the first command if you just add `--build` and the `--build-arg` to the `up` command?

2021-03-10 16:00 UTC, hugh-emerson commented on .travis.yml
> +  - docker-compose --file docker-compose-travis.yml up --exit-code-from todoapp
Also, it doesn't look like anything is being cached currently. https://travis-ci.com/github/jaybee1971/DevOps-Course-Starter/builds/218706804

Probably because you're missing `cache_from` in your docker-compose yaml file

2021-03-10 16:00 UTC, hugh-emerson commented on Dockerfile
> +ENTRYPOINT ["sh", "entrypoint-heroku.sh"]
It's a bit weird to have a whole separate stage and entrypoint-heroku.sh file, instead of just deploying the "prod" image. The exercise implies that you're using Heroku as your production environment.
Not only have you created more code/files, there is surprising behaviour e.g. you have a gunicorn_conf.py file that's used by "prod" but not Heroku

If the only reason was for the $PORT variable, you should: 
- Make the prod stage use the PORT variable instead of hardcoding it in gunicorn_conf.py
- Set a default value. Either with `ENV PORT=5000` or with `--bind 0.0.0.0:${PORT:-5000}` in the gunicorn command
Or `os.getenv('PORT', '5000')` in the conf.py file.

2021-03-10 22:28 UTC, jaybee1971 commented on Dockerfile
> +ENV PORT=${PORT}
I think this was a case of I changed a couple of things and got it working in Heroku and thought this helped it work... based on your other comments I understand where to set PORT now and have removed this plus the whole additional build section in my docker file

2021-03-10 22:30 UTC, jaybee1971 commented on docker_push
> +echo docker login --username=_ --password=${HEROKU_API_KEY} registry.heroku.com
I have done as advised.  I did see the error but didn't fully understand it and thought I had pushed a working build, but now realise that build was pushed from my local testing the commands for the script.  I have updated as advised

2021-03-10 22:31 UTC, jaybee1971 commented on Dockerfile
> +ENTRYPOINT ["sh", "entrypoint-heroku.sh"]
yep, now I understand the PORT part I have removed this and can use the prod-build section locally and remotely

2021-03-10 22:32 UTC, jaybee1971 commented on .travis.yml
> +  - docker-compose --file docker-compose-travis.yml up --exit-code-from todoapp
I had it like that originally and it was failing... could have been a typo, but splitting out the build and up then seemed to work so I left it.  I have left this for now, will review later if everything else works, as this is more aesthetic

2021-03-22 13:53 UTC, hugh-emerson commented
Hm, the latest deployment failed. https://travis-ci.com/github/jaybee1971/DevOps-Course-Starter/jobs/489866315
But the error is an auth failure when pushing to Docker Hub. Possibly the password is wrong? Pulls also failed.

I'll still approve this because the actual changes look fine to me. But you should see if you can fix that.

2021-03-25 11:01 UTC, merged