Module 9
jaybee1971/DevOps-Course-Starter pull request #12
Opened 2021-04-06 12:11 UTC by jaybee1971

All steps done + stretch task to create script to migrate Trello data to MongoDB

2021-04-22 17:20 UTC, JackMead requested changes
This looks good, and nice work on the stretch goal. I've left a few comments below, but the main issue here is that when I try to run the app with a fresh mongo db, the app doesn't handle the missing statuses gracefully which leads to errors. The app should ideally handle that gracefully and allow those statuses to be missing, or your script to port data could consider handling that case

2021-04-22 17:20 UTC, JackMeadDev commented on .travis.yml
>      - secure: TAtZ3ZDXZLhG7PeJBqutF6xXztmu1ZbZXc7ub3G7goSd5xQXcjWkPAyeOMBwIUEj4sRIUn/oWT/XVQejBjkHPO/KCrybd/yopHpVqZDFfGwD064v7EVZJisi4kcmfDzUGsAeZdNa2p1O1WUuhNVONzuqTEinarTS5GH5tS9S3quwdBKgTiyhzbV9e
Some of these are now outdated secrets - API_KEY, API_TOKEN, BOARD_ID which we should remove. Travis doesn't make this particularly easy, but the order of secrets in this file should match the order they're spat out, i.e.
```
export FLASK_APP=todo_app.app
$ export FLASK_ENV=production
$ export API_KEY=[secure]
$ export API_TOKEN=[secure]
$ export BOARD_ID=[secure]
$ export MONGO_URL=[secure]
```

2021-04-22 17:20 UTC, JackMeadDev commented on README.md
> +## Mongo DB
Nice clear documentation, it would be nice to also update your `.env.template` file to match the latest set of environment variables

2021-04-22 17:20 UTC, JackMeadDev commented on todo_app/app.py
> +    def get_mongo_todo_list():
Minor, but it's worth noting how many lines you've changed in this file because our persistence solution changed. Having these names independent of that (e.g. without `trello` or `mongo`) would make this a little easier to maintain; similarly with the functions

2021-04-22 17:20 UTC, JackMeadDev commented on todo_app/app.py
> +                print(mongo_id)
Print statement left in from dev I suspect

2021-04-22 17:20 UTC, JackMeadDev commented on todo_app/mongo_db.py
> +    return [list_data.mongo_id for list_data in get_mongo_todo_statuses() if list_data.status == card_status][0]
Really minor, but a slightly clearer way of writing this would be using python's `next` keyword, which allows us to get the next (or in this case, first) element that matches the condition, rather than finding them all and then taking the first index, e.g. here
`return next(list_data.mongo_id for list_data in get_mongo_todo_statuses() if list_data.status == card_status)`

2021-04-22 17:20 UTC, JackMeadDev commented on todo_app/templates/index.html
> +                                <select class="custom-select" name="{{ todo_item.mongo_id }}" form="{{ todo_item.mongo_id }}">
Similarly to a previous comment - having this as `id` would keep your changes more confined for future, rather than having mongo/trello referenced everywhere

2021-04-23 14:54 UTC, jaybee1971 commented on .travis.yml
>      - secure: TAtZ3ZDXZLhG7PeJBqutF6xXztmu1ZbZXc7ub3G7goSd5xQXcjWkPAyeOMBwIUEj4sRIUn/oWT/XVQejBjkHPO/KCrybd/yopHpVqZDFfGwD064v7EVZJisi4kcmfDzUGsAeZdNa2p1O1WUuhNVONzuqTEinarTS5GH5tS9S3quwdBKgTiyhzbV9e
removed

2021-04-23 14:55 UTC, jaybee1971 commented on README.md
> +## Mongo DB
yep, oversight on my part.
I have also updated the readme to give more clarity on minimum mongoDb collection requirements + schema

2021-04-23 14:56 UTC, jaybee1971 commented on todo_app/app.py
> +    def get_mongo_todo_list():
totally agree... one for the future, would like to move onto exercise 10 as priority

2021-04-23 14:57 UTC, jaybee1971 commented on todo_app/mongo_db.py
> +    return [list_data.mongo_id for list_data in get_mongo_todo_statuses() if list_data.status == card_status][0]
I'll look at this during exercise10 or in future, thx

2021-04-23 14:57 UTC, jaybee1971 commented on todo_app/templates/index.html
> +                                <select class="custom-select" name="{{ todo_item.mongo_id }}" form="{{ todo_item.mongo_id }}">
agreed, will probably refactor at some point

2021-04-23 14:57 UTC, jaybee1971 commented on todo_app/app.py
> +                print(mongo_id)
thx, removed

2021-04-23 15:00 UTC, jaybee1971 commented
Please review again, I have updated the script to add the default status columns and the readme to explain the collections expected... I sort of regret changing the default Trello columns back in the first exercises :) it has caused me loads of issues over the course, but then I might not have learnt as much if I left them as default

2021-05-06 10:14 UTC, JackMead approved these changes
Thanks for making those changes, I was able to run your app locally with little effort with that extra setup. I've noted a typo in the trello_to_mongo script that we should fix up before merging, but otherwise happy for you to do so when you're ready

2021-05-06 10:14 UTC, JackMead commented on trello_to_mongo.py
> +db.todo_statuses.insertMany([
Slight typo here, should be `insert_many` rather than `insertMany`, but I'm happy that with that tweak that let's me get to a working app

2021-05-06 19:29 UTC, merged