Module 3
jaybee1971/DevOps-Course-Starter pull request #5
Opened 2020-09-21 18:39 UTC by jaybee1971

there is still work to do to complete all the tasks.  Most of part 1 is done.  Creating the test app, the structure is there, but not had time to create all the mocked responses.  Selenium, I have a basic working browser test for Chrome that launches root nd checks for app name.  I will try and do more as we work through module 4

2020-09-25 17:16 UTC, hugh-emerson requested changes
Looking shiny 👍 

For us to consider this submission complete, we need at least one working test of each type. Also I should be able to just follow the README and run the tests. See my other comments for some pointers. 

I could make some suggestions for small improvements but I'll save them for after the tests are all running.

2020-09-25 17:16 UTC, hugh-emerson commented on .env.test
> +BOARD_ID=5f2fb12345fda60cf038d7ff
You should not have real credentials here.

2020-09-25 17:16 UTC, hugh-emerson commented on flask_config.py
> +    def __init__(self):
Good to add a constructor 👍

2020-09-25 17:16 UTC, hugh-emerson commented on tests/test_app.py
> +def test_index_page(mock_get_requests, client):
You need a decorator before this function that sets up mock_get_requests. i.e. on a line before this one, add `@patch('requests.get')`
And then inside the test function, you need to configure the fake Trello behaviour with ` mock_get_requests.side_effect = your_own_function`


Alternatively you can define a fixture like the `client` one, but the exercise brief asks you to use `@patch`

2020-09-25 17:16 UTC, hugh-emerson commented on tests/test_app.py
> +
After making the request to your server, assert something about the response.

E.g. Check its status code is equal to 200 or `assert 'My Task Name' in response.data.decode()` if you make your mock Trello request return a card with that name.

2020-09-25 17:16 UTC, hugh-emerson commented on tests/test_browser.py
> +
This test will only ever work if you start the app yourself. And then there is the problem that your test is using your running app - e.g. if your test creates cards, it will create them on your actual board.

The exercise brief gives you the solution to this in step 2 of the Selenium section. You should define a fixture that will start an instance of the app, and then you apply that fixture to your test function `test_python_home` by adding it as a parameter.

2020-09-25 17:16 UTC, hugh-emerson commented on tests/test_todos.py
> +import pytest
You need to add `pytest` and `selenium` to your list of dependencies (in requirements.txt)

2020-09-25 17:16 UTC, hugh-emerson commented on README.md
> +Use the .env.template to create your own entries
You should also add a section mentioning the tests, how to run them, and prerequisites like chromedriver.exe

2020-09-25 17:16 UTC, hugh-emerson commented
> there is still work to do to complete all the tasks. Most of part 1 is done. Creating the test app, the structure is there, but not had time to create all the mocked responses. Selenium, I have a basic working browser test for Chrome that launches root nd checks for app name. I will try and do more as we work through module 4

That's absolutely fine. Module 3 is definitely a larger exercise and it's not necessary to complete it before working on the next few. So do focus on the other doing exercises in sync with the reading material & workshop. You can revisit this another month, when that module is easier than average.

2020-09-28 14:06 UTC, jaybee1971 commented on .env.test
> +BOARD_ID=5f2fb12345fda60cf038d7ff
they aren't real credentials, I randomly changed values from my real ones... perhaps it is better to use something completely different to the Trello format?

2020-10-02 16:32 UTC, hugh-emerson commented on .env.test
> +BOARD_ID=5f2fb12345fda60cf038d7ff
Ah okay, that's fine. Yeah I'd normally make it clearer by setting e.g. `API_KEY=test-api-key`. Plus it means tests can verify that a request was made with the query param "key=test-api-key" and it's all easy to read.
But this is fine - sorry I assumed they were real.

2020-10-09 09:24 UTC, merged